### ISSUE TITLE
Livereload server-side changes

### ISSUE THREAD

**Issue by sameetandpotatoes** [acm-uiuc/groot-desktop-frontend#79]
- If we make changes to server side code, we have to quit the app and restart it. It would be nice if we could implement livereloading so that any change to the codebase (in development) automatically restarts the UI service.

- Would require us to use bower (starting point: https://github.com/livereload/livereload-js)

**Comment by aashishkapur** [comment]
Thoughts of using [nodemon](https://github.com/remy/nodemon) instead?

**Comment by bcongdon** [comment]
Definitely worth looking into

**Comment by aashishkapur** [comment]
Looks like nodemon is just a simple change on the spinup script, while using livereload is a little more involved. I'll open a PR.

**Comment by sameetandpotatoes** [comment]
Yeah I'm fine with it as long as it works with modifying less files, and controller logic

**Comment by pranaygp** [comment]
> Would require us to use bower (starting point: https://github.com/livereload/livereload-js)

I don't think that quite true. In fact, the repo itself emphasizes that bundling in the live-reload script is a bad idea, and instead you should just use this built into a tool (I've used a chrome extension for this and then later switched to [Blisk](https://blisk.io/) and now hot-reload with react). 

Since you aren't using react, but you'd still like this feature, I'd definitely recommend giving [Blisk](https://blisk.io/) a go.

Sorry for the "stackoverflow type" response by suggesting you do something else :P

**Comment by bcongdon** [comment]
Resolved by using `nodemon`.
